### ISSUE TITLE
Unable to configure Flood settings

### ISSUE THREAD

**Issue by imjustafox** [Shadowghost/rtorrent-flood-wireguard-docker#2]
Been using this for a hot second, and I love it. Works excellently and I almost never need to touch it, however I do have one issue. It appears that flood's settings are ephemeral and I have no clue how to force them to stay the same, which causes issues during reboots of the host, as I then need to reconfigure flood by hand.  Any advice with managing that portion?

Here's what flood defaults to upon `docker-compose up -d` 
![image](https://user-images.githubusercontent.com/26676249/180918139-51d27789-365f-42f0-bdcf-b67177483c00.png)

**Comment by Shadowghost** [comment]
That's the default set in `/home/torrent/.rtorrent.rc`. If you don't mount a local config at that location on recreation the changes are lost.
